embroidery365/about/urls.py
from django.conf.urls import url

from . import views

app_name = 'about'

urlpatterns = [
    url(r'^$', views.about_view, name='about'),
]

embroidery365/cart/urls.py
from django.conf.urls import url

from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_view, name='cart'),
    url(r'^remove-from-cart/', views.remove_from_cart_view, name='remove_from_cart'),
    url(r'^checkout/', views.checkout_cart_view, name='checkout_cart'),
]

embroidery365/contact/urls.py
from django.conf.urls import url

from . import views

app_name = 'contact'

urlpatterns = [
    url(r'^$', views.contact_view, name='contact'),
    # url(r'^update_people/$', views.update_people_view, name='update_people'),
]

embroidery365/embroidery365/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts.views import (login_view, register_view, logout_view, account_manager_view, update_account_view)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls'), name='home'),
    url(r'^products/', include('products.urls'), name='products'),
    url(r'^contact/', include('contact.urls'), name='contact'),
    url(r'^about/', include('about.urls'), name='about'),
    url(r'^orders/', include('orders.urls'), name='orders'),
    url(r'^builder/', include('builder.urls'), name='builder'),
    url(r'^cart/', include('cart.urls'), name='cart'),
    url(r'^dashboard/', include('admin_dashboard.urls'), name='dashboard'),
    url(r'^login/', login_view, name='login'),
    url(r'^myaccount/', account_manager_view, name='myaccount'),
    url(r'^update-info', update_account_view, name='update_info'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^register/', register_view, name='register'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

embroidery365/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

embroidery365/orders/urls.py
from django.conf.urls import url

from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^$', views.orders_view, name='orders'),
    # url(r'^update_people/$', views.update_people_view, name='update_people'),
]

embroidery365/products/urls.py
from django.conf.urls import url

from . import views

app_name = 'products'

urlpatterns = [
    url(r'^$', views.products_view, name='products'),
    url(r'^shirts/', views.shirts_view, name='shirts'),
    url(r'^jackets/', views.jackets_view, name='jackets'),
    url(r'^hats/', views.hats_view, name='hats'),
    url(r'^backpacks/', views.backpacks_view, name='backpacks'),
    url(r'^custom_items/', views.custom_items_view, name='custom_items'),
]

embroidery365/about/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth.models import User

from builder.models import Order


def about_view(request):
    try:
        user_object = User.objects.get(username=request.user.username)
        current_user = "{0} {1}".format(user_object.first_name, user_object.last_name)

        current_user_pk = request.user.pk
        orders = Order.objects.filter(customer__pk=current_user_pk)

        context = {
            'current_user': current_user,
            'nitems_in_cart': len(orders),
        }
    except:
        context = {}

    return render(request, 'about/about.html', context)

embroidery365/about/templates/about/about.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>

  {% load static %}

  {# ADD CSS #}

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Scroll Page CSS -->

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.9.4/jquery.fullpage.css">

  <!-- Local CSS -->
  <link rel="stylesheet" href="{% static 'home/css/style.css' %}">

  <link rel="icon" href="{% static 'home/img/favicon.png' %}" sizes="16x16 32x32" type="image/png">

</head>
<body>
  <div id="wrapper">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand pull-left" href="{% url 'home:index' %}"><img src="{% static 'home/img/365DE_mini_logo.png' %}" id="brand-logo" alt=""></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        {% comment %}
        <ul class="nav navbar-nav text-center">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'products:shirts' %}">Shirts</a></li>
              <li><a href="{% url 'products:jackets' %}">Jackets</a></li>
              <li><a href="{% url 'products:hats' %}">Hats</a></li>
              <li><a href="{% url 'products:backpacks' %}">Backpacks</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'products:custom_items' %}">Custom Items</a></li>
            </ul>
          </li>
          <li><a href="#">Services <span class="sr-only">(current)</span></a></li>
        </ul>
        {% endcomment %}

        <ul class="nav navbar-nav navbar-right text-center">
          <li><a href="{% url 'contact:contact' %}">Contact Us</a></li>
          <li><a href="{% url 'about:about' %}">About Us</a></li>

          {% if current_user %}
          <li class="dropdown active-user">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-user"></span>
            <strong>{{ current_user }}
              <span class="caret"></span>
            </strong></a>
            <ul class="dropdown-menu">
              {% if request.user.is_superuser %}
              <li><a href="{% url 'admin_dashboard:dashboard' %}">Admin Dashboard</a></li>
              {% endif %}
              <li><a href="{% url 'myaccount' %}">Manage Account</a></li>
              <li><a href="{% url 'orders:orders' %}">Your Orders</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'logout' %}" id="signout-btn">
                <span class="glyphicon glyphicon-off"></span> Log Out</a>
              </li>
            </ul>
          </li>
          <li><a href="{% url 'cart:cart' %}"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> {% if current_user %}<span class="badge">{{ nitems_in_cart }}</span>{% endif %}</a></li>
          {% else %}
          <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Sign In</a></li>
          <li><a href="{% url 'register' %}"><span class="glyphicon glyphicon-pencil"></span> Sign Up</a></li>
          {% endif %}
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div id="content">
  <div class="container">
    <h1 class="page-title text-center">About Us</h1>
    <hr>

    <div class="row">
      <div class="lg-col-12 col-md-12 col-sm-12 col-xs-12">
        <div class="thumbnail">
          <img src="http://via.placeholder.com/300.png/09f/fff" alt="...">
          <div class="caption">
            <h3>Thumbnail label</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="lg-col-12 col-md-12 col-sm-12 col-xs-12">
        <div class="thumbnail">
          <img src="http://via.placeholder.com/300.png/09f/fff" alt="...">
          <div class="caption">
            <h3>Thumbnail label</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>

  <button type="button" name="button" class="back-to-top" data-placement="left" data-toggle="tooltip" title="Back to Top"><span class="glyphicon glyphicon-chevron-up"></span></button>

  <div id="footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-2 text-center"><img src="{% static 'home/img/365DE_mini_logo.png' %}" alt=""></div>
        <div class="col-lg-2 text-center"><a href="{% url 'home:index' %}">Home</a></div>
        <div class="col-lg-2 text-center"><a href="{% url 'contact:contact' %}">Contact Us</a></div>
        <div class="col-lg-2 text-center"><a href="{% url 'about:about' %}">About Us</a></div>
        {% if not current_user %}
        <div class="col-lg-2 text-center"><a href="{% url 'login' %}">Sign In</a></div>
        <div class="col-lg-2 text-center"><a href="{% url 'register' %}">Sign Up</a></div>
        {% else %}
        <div class="col-lg-2 text-center"><a href="{% url 'cart:cart' %}">Your Cart</a></div>
        <div class="col-lg-2 text-center"><a href="{% url 'orders:orders' %}">Your Orders</a></div>
        {% endif %}
      </div><br>
      <div class="row">
        <div class="col-lg-12"><p class="text-muted text-center">Copyright (c) 2017 365 Digitizing and Embroidery All Rights Reserved.</p></div>
      </div>
    </div>
  </div>
</div>

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <!-- Full Page JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.9.4/jquery.fullpage.extensions.min.js"></script>
  <!-- Local JS -->
  <script src="{% static 'home/js/main.js' %}"></script>

  <script type="text/javascript">
    $(document).ready(function() {
      var myvar = 100;
      var offset = 250;
      var duration = 300;

      $(window).scroll(function() {
        if ($(this).scrollTop() > offset) {
          $(".back-to-top").fadeIn(duration);
        } else {
          $(".back-to-top").fadeOut(duration);
        }
      });

      $(".back-to-top").click(function(event) {
        event.preventDefault();

        $("html, body").animate({scrollTop: 0}, duration);

        return false;
      });
    });


    $('.back-to-top').on('mouseenter', function(){
      $('.back-to-top').tooltip('show');
    });

    $('.back-to-top').on('mouseleave', function(){
      $('.back-to-top').tooltip('hide');
    });
  </script>


</body>
</html>