embroidery365/about/urls.py
from django.conf.urls import url

from . import views

app_name = 'about'

urlpatterns = [
    url(r'^$', views.about_view, name='about'),
]

embroidery365/builder/urls.py
from django.conf.urls import url

from . import views

app_name = 'builder'

urlpatterns = [
    url(r'^$', views.builder_view, name='builder'),
    url(r'^add-to-cart/', views.add_to_cart, name='add_to_cart'),
    # url(r'^update_people/$', views.update_people_view, name='update_people'),
]

embroidery365/cart/urls.py
from django.conf.urls import url

from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_view, name='cart'),
    url(r'^remove-from-cart/', views.remove_from_cart_view, name='remove_from_cart'),
    url(r'^checkout/', views.checkout_cart_view, name='checkout_cart'),
]

embroidery365/embroidery365/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts.views import (login_view, register_view, logout_view, account_manager_view, update_account_view)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls'), name='home'),
    url(r'^products/', include('products.urls'), name='products'),
    url(r'^contact/', include('contact.urls'), name='contact'),
    url(r'^about/', include('about.urls'), name='about'),
    url(r'^orders/', include('orders.urls'), name='orders'),
    url(r'^builder/', include('builder.urls'), name='builder'),
    url(r'^cart/', include('cart.urls'), name='cart'),
    url(r'^dashboard/', include('admin_dashboard.urls'), name='dashboard'),
    url(r'^login/', login_view, name='login'),
    url(r'^myaccount/', account_manager_view, name='myaccount'),
    url(r'^update-info', update_account_view, name='update_info'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^register/', register_view, name='register'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

embroidery365/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

embroidery365/orders/urls.py
from django.conf.urls import url

from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^$', views.orders_view, name='orders'),
    # url(r'^update_people/$', views.update_people_view, name='update_people'),
]

embroidery365/cart/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from builder.models import Order
from django.utils import timezone


class PlacedOrder(models.Model):
    customer = models.ForeignKey(User, default=1)
    order_number = models.CharField(max_length=255, default=1)
    total = models.DecimalField(max_digits=10, decimal_places=2) #models.FloatField(default=0.0)
    created = models.DateField(auto_now_add=True)
    status = models.IntegerField(default=0)
    active = models.BooleanField(default=True)

    def __str__(self):
        return "{0} {1}: #{2}".format(self.customer.first_name, self.customer.last_name, self.order_number)


class OrderItem(models.Model):
    placed_order = models.ForeignKey(PlacedOrder, on_delete=models.CASCADE)

    customer = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    order_base_item = models.CharField(max_length=255, default='')
    order_style = models.CharField(max_length=255, default='')
    order_logo = models.ImageField(blank=True)
    order_item_placement = models.CharField(max_length=255, default='')
    order_logo_width = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    order_logo_height = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    order_details = models.TextField(blank=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    extra_details = models.TextField(blank=True, null=True)
    logo_colors = models.TextField(blank=True, null=True)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return "{0} {1} {2}".format(self.customer, self.order_base_item, self.order_style)

embroidery365/cart/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from cart.models import PlacedOrder, OrderItem
from builder.models import Order

from datetime import datetime


from builder.models import Order


@login_required(login_url='login')
def cart_view(request):
    current_user_pk = request.user.pk
    orders = Order.objects.filter(customer__pk=current_user_pk)

    current_user = User.objects.get(pk=current_user_pk)

    context = {
        'all_orders': orders,
        'current_user': "{0} {1}".format(current_user.first_name, current_user.last_name),
        'nitems_in_cart': len(orders),
        'cart_total': sum([i.total for i in orders])
    }
    return render(request, 'cart/cart.html', context)


@login_required(login_url='login')
def remove_from_cart_view(request):
    item_to_remove = request.POST.get('item-to-remove')

    order_to_remove = Order.objects.get(pk=item_to_remove)
    order_to_remove.delete()

    return redirect('/cart')


@login_required(login_url='login')
def checkout_cart_view(request):
    current_user_pk = request.user.pk
    orders = Order.objects.filter(customer__pk=current_user_pk)

    user = User.objects.get(pk=current_user_pk)

    total = sum([o.total for o in orders])

    placed_order_object = PlacedOrder(customer=user, order_number=make_unique_order_number(request), total=total)
    placed_order_object.save()

    for order in orders:
        noi = OrderItem(placed_order=placed_order_object, customer=order.customer, order_base_item=order.order_base_item,
                        order_style=order.order_style, order_logo=order.order_logo,
                        order_item_placement=order.order_item_placement, order_logo_width=order.order_logo_width,
                        order_logo_height=order.order_logo_height, order_details=order.order_details,
                        total=order.total, extra_details=order.extra_details,
                        logo_colors=order.logo_colors, created=order.created
                        )
        noi.save()

        order.delete()

    return redirect('/orders')


def make_unique_order_number(request):
    ext = request.user.first_name[0] + request.user.last_name[0]
    return ext.upper() + datetime.now().strftime('%m%d%y%H%M%S')

embroidery365/cart/templates/cart/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>

  {% load static %}

  {# ADD CSS #}

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Scroll Page CSS -->

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.9.4/jquery.fullpage.css">

  <!-- Local CSS -->
  <link rel="stylesheet" href="{% static 'home/css/style.css' %}">

  <link rel="icon" href="{% static 'home/img/favicon.png' %}" sizes="16x16 32x32" type="image/png">

</head>
<body>
  <div id="wrapper">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand pull-left" href="{% url 'home:index' %}"><img src="{% static 'home/img/365DE_mini_logo.png' %}" id="brand-logo" alt=""></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        {% comment %}
        <ul class="nav navbar-nav text-center">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'products:shirts' %}">Shirts</a></li>
              <li><a href="{% url 'products:jackets' %}">Jackets</a></li>
              <li><a href="{% url 'products:hats' %}">Hats</a></li>
              <li><a href="{% url 'products:backpacks' %}">Backpacks</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'products:custom_items' %}">Custom Items</a></li>
            </ul>
          </li>
          <li><a href="#">Services <span class="sr-only">(current)</span></a></li>
        </ul>
        {% endcomment %}

        <ul class="nav navbar-nav navbar-right text-center">
          <li><a href="{% url 'contact:contact' %}">Contact Us</a></li>
          <li><a href="{% url 'about:about' %}">About Us</a></li>

          {% if current_user %}
          <li class="dropdown active-user">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-user"></span>
            <strong>{{ current_user }}
              <span class="caret"></span>
            </strong></a>
            <ul class="dropdown-menu">
              {% if request.user.is_superuser %}
              <li><a href="{% url 'admin_dashboard:dashboard' %}">Admin Dashboard</a></li>
              {% endif %}
              <li><a href="{% url 'myaccount' %}">Manage Account</a></li>
              <li><a href="{% url 'orders:orders' %}">Your Orders</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'logout' %}" id="signout-btn">
                <span class="glyphicon glyphicon-off"></span> Log Out</a>
              </li>
            </ul>
          </li>
          {% else %}
          <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Sign In</a></li>
          {% endif %}



          <li><a href="{% url 'cart:cart' %}"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> {% if current_user %}<span class="badge">{{ nitems_in_cart }}</span>{% endif %}</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div id="content">
  <div class="container" id="my-cart">
    <div class="row" id="cart-header">
      <div class="col-lg-12">
        <h1 class="page-title text-center">My Cart</h1>
        <h2 class="text-center">Cart Total: <strong>${{ cart_total }}</strong></h2>
      </div>
    </div>

    {% if all_orders|length > 0%}

    <div class="row">
      <div class="col-lg-12">
        <button class="btn btn-warning btn-lg btn-block" data-toggle="modal" data-target="#myModal">Proceed to Checkout</button>
      </div>
    </div><br>

    <div class="panel-group">
    {% for order in all_orders %}
      <div class="panel panel-primary">
        <div class="panel-heading">
          <div class="row text-center">
            <div class="col-lg-4">
              <h3>Item Created: {{ order.created }}</h3>

            </div>
            <div class="col-lg-4">
              <h3>Total: <strong>${{ order.total }}</strong></h3>
            </div>
            <div class="col-lg-4">
              <h3>Item #: {{ order.pk }}</h3>
            </div>
          </div>
        </div>
        <div class="panel-body">
          {{ order.order_details|safe}}
          <hr>
          <div class="row">
            <div class="col-lg-6">
              <h4 class="text-center">Order Attachments:</h4>
              <img src="{{ order.order_logo.url }}" alt="..." class="img-responsive order_img">
            </div>

            <div class="col-lg-6 text-center" class="extra-details">
              <h4>Order Specifications:</h4>
              {% if order.extra_details|length > 0 %}
              <span class="text-success"><h4><em>{{ order.extra_details }}</em></h4></span>
              {% else %}
              <span class="text-danger"><h4><em>No Specifications Included</em></h4></span>
              {% endif %}
            </div>
          </div>
          {{ order.logo_colors|safe }}
        </div>
        <div class="panel-footer">
          <div class="row">
            <div class="col-lg-12">
              <form class="remove-from-cart-form" action="{% url 'cart:remove_from_cart' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="item-to-remove" value="{{ order.pk }}">
                <button type="submit" class="btn btn-danger btn-block" name="button">Remove Items</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
    <div class="row">
      <div class="col-lg-12">
        <button class="btn btn-warning btn-lg btn-block" data-toggle="modal" data-target="#myModal">Proceed to Checkout</button>
      </div>
    </div><br>
    <div class="row">
      <div class="col-lg-12">
        <a href="{% url 'builder:builder' %}" class="hero-btn inverse" id="start-project-from-cart">Add an Item</a>
      </div>
    </div>
    {% else %}
    <div class="row">
      <div class="col-lg-12">
        <h1 class="text-muted text-center">There are no items in your cart.</h1>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6 col-lg-offset-3">
        <a href="{% url 'builder:builder' %}" class="hero-btn inverse" id="start-project-from-cart">Start a Project</a>
      </div>
    </div>

    {% endif %}
  </div>

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h2 class="modal-title text-center" id="myModalLabel"><strong><span class="glyphicon glyphicon-check"></span> Checkout</strong></h2>
        </div>
        <div class="modal-body">
          <h2 class="text-center">Estimated Total: <strong>${{ cart_total }}</strong></h2>
          <h3 class="text-center">We won't charge your card until you approve the sample design.</h3>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
          <a href="{% url 'cart:checkout_cart' %}" class="btn btn-success">Checkout</a>
          <!--
          <form id="checkout-form" action="{% url 'cart:checkout_cart' %}" method="post">
            {% csrf_token %}
          </form>-->

        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
  </div>
  <button type="button" name="button" class="back-to-top" data-placement="left" data-toggle="tooltip" title="Back to Top"><span class="glyphicon glyphicon-chevron-up"></span></button>

  <div id="footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-2 text-center"><img src="{% static 'home/img/365DE_mini_logo.png' %}" alt=""></div>
        <div class="col-lg-2 text-center"><a href="{% url 'home:index' %}">Home</a></div>
        <div class="col-lg-2 text-center"><a href="{% url 'contact:contact' %}">Contact Us</a></div>
        <div class="col-lg-2 text-center"><a href="{% url 'about:about' %}">About Us</a></div>
        {% if not current_user %}
        <div class="col-lg-2 text-center"><a href="{% url 'login' %}">Sign In</a></div>
        <div class="col-lg-2 text-center"><a href="{% url 'register' %}">Sign Up</a></div>
        {% else %}
        <div class="col-lg-2 text-center"><a href="{% url 'cart:cart' %}">Your Cart</a></div>
        <div class="col-lg-2 text-center"><a href="{% url 'orders:orders' %}">Your Orders</a></div>
        {% endif %}
      </div><br>
      <div class="row">
        <div class="col-lg-12"><p class="text-muted text-center">Copyright (c) 2017 365 Digitizing and Embroidery All Rights Reserved.</p></div>
      </div>
    </div>
  </div>
</div>

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <!-- Full Page JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.9.4/jquery.fullpage.extensions.min.js"></script>
  <!-- Local JS -->
  <script src="{% static 'home/js/main.js' %}"></script>
  <!-- <script src="{% static 'builder/js/shirt.js' %}"></script> -->

  <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.12/p5.js"></script>
  <!-- <script src="{% static 'builder/js/sketch.js' %}"></script> -->

  <script type="text/javascript">
    $(document).ready(function() {
      var myvar = 100;
      var offset = 250;
      var duration = 300;

      $(window).scroll(function() {
        if ($(this).scrollTop() > offset) {
          $(".back-to-top").fadeIn(duration);
        } else {
          $(".back-to-top").fadeOut(duration);
        }
      });

      $(".back-to-top").click(function(event) {
        event.preventDefault();

        $("html, body").animate({scrollTop: 0}, duration);

        return false;
      });
    });


    $('.back-to-top').on('mouseenter', function(){
      $('.back-to-top').tooltip('show');
    });

    $('.back-to-top').on('mouseleave', function(){
      $('.back-to-top').tooltip('hide');
    });
  </script>

</body>
</html>